# Use these tags to create a custom format : 
#
# %D - Day of week
# %h - Hours (in 12h format)
# %H - Hours (in 24h format)
# %m - Minutes
# %a - AM / PM
# %d - Day of month
# %t - Suffix after the day (In the english version of the game : "st", "nd", "rd" or "th")
# %o  - " of " (used between the date and the month: 17th of ..., contains spaces)
# %M  - Month of year (as a number)
# %L  - Month of year (full name)
# %E  - Era (always 4E)
# %y  - Year
# %i  - Immersive time of day

# Example (vanilla format):
# Turdas, 1:13 PM, 21st of Last Seed, 4E 201
# %D, %h:%m %a, %d%t%o%M, %E %y
#
# Warning: too long strings may get trimmed. The actual character limit depends on the content. It is recommended to try the longest possible date before use.
# You can force display any date if you change the format code to that specific date, like this:

# sTimeFormat="Loredas, 11:13 PM, 21st of Morning Star, 4E 201"

# This will always display "Loredas, 11:13 PM, 21st of Morning Star, 4E 201" regardless of the actual in-game time. 
[FORMAT]
sTimeFormat = %D, %H:%m, %d%t%o%L, %E %y

# Format without year(used in Sleep / Wait menu)
sTimeFormatNoYear = %D, %H:%m, %d%t%o%L

# If enabled a leading zero will be added to the hour if it's less than 10 (8:30 -> 08:30)
# Only for 24 hour time!
bLeadingZeroHour = false

# If enabled a leading zero will be added to the day of month if it's less than 10 (7 -> 07)
bLeadingZeroDay = false

# If enabled a leading zero will be added to the month if it's less than 10 (7 -> 07)
bLeadingZeroMonth = false


# These names are used by the %i tag. The name of the interval the current in-game hour falls into is inserted into the format. You can override them below, or leave the fields empty to use the default values.
[IMMERSIVE_NAME_OVERRIDES]
s00_01 =
s01_02 =
s02_03 =
s03_04 =
s04_05 =
s05_06 =
s06_07 =
s07_08 =
s08_09 =
s09_10 =
s10_11 =
s11_12 =
s12_13 =
s13_14 =
s14_15 =
s15_16 =
s16_17 =
s17_18 =
s18_19 =
s19_20 =
s20_21 =
s21_22 =
s22_23 =
s23_24 =
