#ifndef	TIMEFORMATCHANGER_VERSION_INCLUDED
#define TIMEFORMATCHANGER_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define TIMEFORMATCHANGER_VERSION_MAJOR		1
#define TIMEFORMATCHANGER_VERSION_MINOR		0
#define TIMEFORMATCHANGER_VERSION_PATCH		0
#define TIMEFORMATCHANGER_VERSION_BETA		0
#define TIMEFORMATCHANGER_VERSION_VERSTRING	MAKE_STR(TIMEFORMATCHANGER_VERSION_MAJOR) "." MAKE_STR(TIMEFORMATCHANGER_VERSION_MINOR) "." MAKE_STR(TIMEFORMATCHANGER_VERSION_PATCH) "." MAKE_STR(TIMEFORMATCHANGER_VERSION_BETA)

#endif
