set(SOURCES
	include/Formatter.h
	include/Hooks.h
	include/ImmersiveNames.h
	include/PCH.h
	include/ModConfigUI.h
	include/Settings.h
	include/version.h
	src/Formatter.cpp
	src/Hooks.cpp
	src/ImmersiveNames.cpp
	src/ModConfigUI.cpp
	src/Settings.cpp
	src/main.cpp
)
